const { createClient } = require('@sanity/client');
const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

dotenv.config({ path: path.resolve(__dirname, '../.env.local') });

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET || 'production',
  useCdn: false,
  token: process.env.SANITY_API_TOKEN,
  apiVersion: '2026-05-13',
});

const bodyContent = fs.readFileSync(path.resolve(__dirname, 'draft-tempmail10min-technical-seo-body.md'), 'utf-8');

const schemaMarkupObj = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "FAQPage",
      "@id": "https://whoisalfaz.me/blog/tempmail10min-technical-seo/#faq",
      "mainEntity": [
        {
          "@type": "Question",
          "name": "Does an Exact Match Domain (EMD) still help SEO in 2026?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "An Exact Match Domain provides a modest initial relevance signal for targeted queries, but search engines apply strict quality thresholds to EMDs. If an EMD has thin content, intrusive ads, or broken technical signals, it is easily penalized by helpful content systems. An EMD only succeeds when backed by real performance, clean architecture, and substantive informational content."
          }
        },
        {
          "@type": "Question",
          "name": "How do you stop search engines from indexing temporary session inboxes?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Add wildcard exclusion directives to your robots.txt file (e.g., Disallow: /*?session=* and Disallow: /*?token=*). Additionally, ensure internal links generated by client-side JavaScript do not output crawlable <a href=\"...\"> anchors containing dynamic session parameters."
          }
        },
        {
          "@type": "Question",
          "name": "Why is an 8-tool benchmark better than standard blog posts?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Google's ranking systems heavily favor primary source information gain. A hands-on benchmark evaluating real delivery latency, domain acceptance, and storage hygiene across 8 competitors provides unique empirical data that cannot be synthesized by automated scrapers, establishing authentic topical authority."
          }
        },
        {
          "@type": "Question",
          "name": "Why document organic growth week by week?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Live documentation keeps the case study accountable, transparent, and grounded in reality. Rather than relying on hindsight or inflated vanity metrics, sharing weekly milestones demonstrates the true operational timeline and tactical adjustments required to scale a utility property from zero."
          }
        }
      ]
    }
  ]
};

const postDoc = {
  _id: 'post-tempmail10min-technical-seo',
  _type: 'post',
  title: 'SEO Lead Case Study: Scaling TempMail10min [Week 1 Live Log]',
  slug: { _type: 'slug', current: 'tempmail10min-technical-seo' },
  description: 'Documenting the live SEO journey of TempMail10min as SEO Lead. Week 1: Launch audit, fixing parameter crawl traps, 8-tool benchmark, and weekly growth tracker.',
  seoTitle: 'TempMail10min SEO Case Study: Week 1 Live Log [2026]',
  seoDescription: 'Documenting the live SEO journey of TempMail10min. Week 1: Launch audit, fixing parameter crawl traps, 8-tool benchmark, and weekly growth tracking.',
  date: '2026-09-17T15:00:00.000Z',
  image: {
    _type: 'image',
    asset: {
      _type: 'reference',
      _ref: 'image-6efa1dd65cc4f90b3318c5224287449abc8a7f89-1376x768-webp'
    }
  },
  categories: [
    { _type: 'reference', _ref: 'pJmrsKLAWC800vFHegUEU1' }, // Architecture Teardowns
    { _type: 'reference', _ref: 'h5g7gmeO9wOK6amcKFpnOQ' }  // SEO & Optimization
  ],
  affiliates: [],
  schemaMarkup: JSON.stringify(schemaMarkupObj, null, 2),
  body: bodyContent
};

async function publish() {
  console.log('Publishing post to Sanity...');
  const res = await client.createOrReplace(postDoc);
  console.log('✅ Successfully published post to Sanity! ID:', res._id);
  
  // Write to draft JSON as record
  fs.writeFileSync(path.resolve(__dirname, '../draft-tempmail10min-technical-seo.json'), JSON.stringify(postDoc, null, 2), 'utf-8');
  console.log('Saved local JSON record at draft-tempmail10min-technical-seo.json');
}

publish().catch(console.error);
